# Generated by Django 4.2.5 on 2023-10-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
