# Generated by Django 4.2.5 on 2024-02-02 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='join_requests',
            field=models.ManyToManyField(blank=True, related_name='join_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
