# Generated by Django 4.2.5 on 2024-03-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='allows_offensive',
            field=models.BooleanField(default=False),
        ),
    ]
