# Generated by Django 4.2.5 on 2024-03-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='anonymous_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
