# Generated by Django 4.2.5 on 2024-03-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delete_offensive',
            field=models.BooleanField(default=False),
        ),
    ]
