# Generated by Django 4.2.5 on 2024-02-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='voter',
            new_name='user',
        ),
    ]
