# Generated by Django 4.2.5 on 2024-02-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hashtag_hashtaginstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='content',
            field=models.CharField(max_length=280, unique=True),
        ),
    ]
