# Generated by Django 4.2.5 on 2023-11-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_repost_original_post_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repost',
            name='additional_content',
        ),
        migrations.RemoveField(
            model_name='repost',
            name='original_post',
        ),
        migrations.RemoveField(
            model_name='repost',
            name='original_post_deleted',
        ),
        migrations.AddField(
            model_name='repost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='core.post'),
        ),
    ]
