# Generated by Django 4.2.5 on 2024-03-04 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_voter_vote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollchoice',
            name='post',
        ),
        migrations.AlterField(
            model_name='pollchoice',
            name='choice_text',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='core.post')),
            ],
        ),
        migrations.AddField(
            model_name='pollchoice',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.poll'),
        ),
    ]
