# Generated by Django 4.2.5 on 2023-10-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_forget_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forget_password_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
