# Generated by Django 4.2.5 on 2023-12-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_messaging_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='category',
            field=models.IntegerField(choices=[(0, 'Hate'), (1, 'Abuse and harassment'), (2, 'Violent speech')], default=2),
        ),
    ]
