# Generated by Django 4.2.5 on 2024-03-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anonymous_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
