# Generated by Django 4.2.5 on 2024-01-03 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_profile_messaging_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
        ),
        migrations.AddConstraint(
            model_name='postpin',
            constraint=models.UniqueConstraint(fields=('pinner', 'post'), name='pinner_post_unique'),
        ),
    ]
