# Generated by Django 4.2.5 on 2023-11-26 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_profile_blocked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blocked_users',
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked',
            field=models.ManyToManyField(blank=True, related_name='blocked', to=settings.AUTH_USER_MODEL),
        ),
    ]
