# Generated by Django 4.2.5 on 2024-03-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pollchoice_post_alter_pollchoice_choice_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollchoice',
            name='choice_votes',
            field=models.IntegerField(default=0),
        ),
    ]
