# Generated by Django 4.2.5 on 2024-03-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pollchoice_choice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
