# Generated by Django 4.2.5 on 2023-11-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notifications_sent_by_alter_notifications_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
