# Generated by Django 4.2.5 on 2023-11-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notifications_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_following',
            field=models.BooleanField(default=False),
        ),
    ]
