# Generated by Django 4.2.5 on 2023-11-06 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_is_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_following',
        ),
    ]
