# Generated by Django 4.2.5 on 2023-11-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_profile_is_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='status',
        ),
    ]
