# Generated by Django 4.2.5 on 2023-12-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_gif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='gif',
        ),
        migrations.AddField(
            model_name='message',
            name='gif_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
