# Generated by Django 4.2.5 on 2023-12-29 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_file_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='message',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
    ]
