# Generated by Django 4.2.5 on 2024-01-02 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_fileupload_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='messageImages')),
                ('message', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
            ],
        ),
    ]
