# Generated by Django 4.2.5 on 2024-01-10 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_alter_reportmessage_reporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmessage',
            name='date_reported',
        ),
        migrations.RemoveField(
            model_name='reportmessage',
            name='reporter',
        ),
        migrations.AddField(
            model_name='reportmessage',
            name='reported',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_reported_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportmessage',
            name='message',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
    ]
