# Generated by Django 4.2.5 on 2024-01-10 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_remove_reportmessage_date_reported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmessage',
            name='reported',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
