# Generated by Django 4.2.5 on 2024-01-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_reportmessage_reported'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportmessage',
            old_name='reported',
            new_name='reporter',
        ),
    ]
