# Generated by Django 4.2.5 on 2024-01-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_gif_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='initiated_by_user1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='initiated_by_user2',
            field=models.BooleanField(default=False),
        ),
    ]
