name: Django CI

on:
  pull_request:
    branches: 
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_DAVRINE }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: ls
        run: ls
      # - name: Checkout
      #   uses: actions/checkout@v3
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

